require:
  - rubocop-performance

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'test/mock/app/**/*'
    - 'test/mock/examples/**/*'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 250

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
