require:
  - rubocop-performance

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'test/mock/app/**/*'
    - 'test/mock/examples/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
