name: Linting
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0
          bundler: 4
          bundler-cache: true

      - name: Run Standard
        run: bundle exec standardrb --fail-level A
